CC = i586-mingw32msvc-gcc
CFLAGS = $(GLOBAL_CFLAGS) $(APP_CFLAGS) $(MINGW_CROSS_CFLAGS) -mwindows
LIB_SUFFIX = .dll
PLATFORM_OFILES = $(MINGW_CROSS_PLATFORM_OFILES)
PLATFORM_LIBS = $(MINGW_CROSS_PLATFORM_LIBS)
DEL_COMMAND = rm -f
DEL_FOLDER_COMMAND = rm -rf
EXE_SUFFIX = .exe

include makefile.common

icon.o : icon.ico icon.rc
	i586-mingw32msvc-windres -o icon.o icon.rc

../$(APP_BUNDLE_NAME).app:
	echo nothing >> ../$(APP_BUNDLE_NAME).app
	@rm -f ../$(APP_BUNDLE_NAME).app
