CC = gcc
CFLAGS = $(COMMON_CFLAGS) -mmacosx-version-min=10.6 -DT3F_DEVELOPER_NAME="\"tcubedsoftware\"" -DT3F_APP_DATA_DIR="\"tcubedsoftware\""
LFLAGS = $(COMMON_LFLAGS) -mmacosx-version-min=10.6 -L/usr/local/lib
LIBS = -framework IOKit -framework AudioToolbox -framework OpenGL -framework OpenAL -framework Cocoa -framework CoreVideo -framework CoreAudio -framework Carbon -framework UniformTypeIdentifiers -lallegro_main-static -lallegro_image-static -lallegro_font-static -lallegro_ttf-static -lallegro_primitives-static -lallegro_audio-static -lallegro_acodec-static -lz -lpng -ljpeg -lvorbis -lopus -logg -lvorbisfile -lopusfile -ldumb -lallegro_dialog-static -lallegro_memfile-static -lallegro_color-static -lallegro-static -lfreetype -lFLAC -lwebp -lsharpyuv
EXE_SUFFIX =
DEL_COMMAND = rm -f

include makefile.common
