CC = gcc
CFLAGS = $(COMMON_CFLAGS)
LFLAGS = $(COMMON_LFLAGS) -mwindows
LIBS = -lallegro_image-static -lallegro_font-static -lallegro_ttf-static -lallegro_primitives-static -lallegro_audio-static -lallegro_acodec-static -lallegro_dialog-static -lallegro_memfile-static -lallegro-static
EX_SUFFIX = .exe
DEL_COMMAND = del /Q

include makefile.common
