CC = gcc
CFLAGS = $(COMMON_CFLAGS) -DT3F_COMPANY="\"t3-i\""
LFLAGS = $(COMMON_LFLAGS)
LIBS = -lallegro_image-static -lallegro_font-static -lallegro_ttf-static -lallegro_primitives-static -lallegro_audio-static -lallegro_acodec-static -lallegro_dialog-static -lallegro_memfile-static -lallegro-static
EXE_SUFFIX = .exe
DEL_COMMAND = rm -f

include makefile.common
