ANDROID_SDK_ROOT = $(HOME)/Development/Tools/android-sdk-macosx
ANDROID_NDK_ROOT = $(HOME)/Development/Tools/android-ndk-r9d
ANDROID_TOOLCHAIN_ROOT = $(HOME)/Development/Tools/android-toolchain
ALLEGRO_SRC_ROOT = $(HOME)/Development/Libraries/allegro5
#INNO_SETUP_COMPILER = 
#DLLS_DIR = 
