CC = i586-mingw32msvc-gcc
CFLAGS = $(GLOBAL_CFLAGS) $(APP_CFLAGS) $(MINGW_CROSS_CFLAGS) -mwindows
LIB_SUFFIX = .dll
PLATFORM_OBJECTS = icon.o $(MINGW_CROSS_PLATFORM_OBJECTS)
PLATFORM_LIBS = $(MINGW_CROSS_PLATFORM_LIBS)
DEL_COMMAND = rm -f
DEL_FOLDER_COMMAND = rm -rf
EXE_SUFFIX = .exe

include makefile.common

icon.o : ../icons/windows_icon.ico icon.rc
	i586-mingw32msvc-windres --include-dir=../icons -o icon.o icon.rc
