####################
# Android Settings #
####################
ANDROID_SDK_ROOT = $(HOME)/Development/Tools/android-sdk-macosx
ANDROID_NDK_ROOT = $(HOME)/Development/Tools/android-ndk-r9d
ANDROID_TOOLCHAIN_ROOT = $(HOME)/Development/Tools/android-toolchain
ALLEGRO_SRC_ROOT = $(HOME)/Development/Libraries/allegro5

#####################
# Mac OS X Settings #
#####################
MACOSX_ARCHITECURES = -arch i386 -arch x86_64
MACOSX_MIN_VERSION = 10.6
MACOSX_COMPILER_SETTINGS = -I/usr/local/include
MACOSX_LINKER_SETTINGS = -L/usr/local/lib

####################
# Windows Settings #
####################
INNO_SETUP_COMPILER = ~/.wine/drive_c/Program\ Files/Inno\ Setup\ 5/Compil32.exe
#DLLS_DIR =
